Cell 1 - Load processed data

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path(r"C:\Users\NickK\OneDrive\Υπολογιστής\github\kaggle_store_sales_forecasting")
PROCESSED_DIR = BASE_DIR / "data" / "processed"

train = pd.read_csv(PROCESSED_DIR / "train_features.csv")

train["date"] = pd.to_datetime(train["date"])

print(train.shape)

(3000888, 21)

Cell 2 - Sort correctly

In [2]:
train = train.sort_values(
    ["store_nbr", "family", "date"]
)

train.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,quarter,...,day_of_week,is_weekend,city,state,type,cluster,dcoilwtico,is_payday,is_national_holiday,earthquake_period
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,...,1,0,Quito,Pichincha,D,13,93.14,0,1,0
1782,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,2013,1,2,1,...,2,0,Quito,Pichincha,D,13,93.14,0,0,0
3564,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,2013,1,3,1,...,3,0,Quito,Pichincha,D,13,92.97,0,0,0
5346,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,2013,1,4,1,...,4,0,Quito,Pichincha,D,13,93.12,0,0,0
7128,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,2013,1,5,1,...,5,1,Quito,Pichincha,D,13,93.12,0,1,0

Cell 3 - Create Lag 7

In [3]:
train["sales_lag_7"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .shift(7)
)

Cell 4 - Create Lag 14

In [4]:
train["sales_lag_14"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .shift(14)
)

Cell 5 - Create Lag 28

In [5]:
train["sales_lag_28"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .shift(28)
)

Cell 6 - Check

In [6]:
train[
    [
        "date",
        "store_nbr",
        "family",
        "sales",
        "sales_lag_7",
        "sales_lag_14",
        "sales_lag_28"
    ]
].head(40)

,date,store_nbr,family,sales,sales_lag_7,sales_lag_14,sales_lag_28
0,2013-01-01,1,AUTOMOTIVE,0.0,NaN,NaN,NaN
1782,2013-01-02,1,AUTOMOTIVE,2.0,NaN,NaN,NaN
3564,2013-01-03,1,AUTOMOTIVE,3.0,NaN,NaN,NaN
5346,2013-01-04,1,AUTOMOTIVE,3.0,NaN,NaN,NaN
7128,2013-01-05,1,AUTOMOTIVE,5.0,NaN,NaN,NaN
8910,2013-01-06,1,AUTOMOTIVE,2.0,NaN,NaN,NaN
10692,2013-01-07,1,AUTOMOTIVE,0.0,NaN,NaN,NaN
12474,2013-01-08,1,AUTOMOTIVE,2.0,0.0,NaN,NaN
14256,2013-01-09,1,AUTOMOTIVE,2.0,2.0,NaN,NaN
16038,2013-01-10,1,AUTOMOTIVE,2.0,3.0,NaN,NaN
17820,2013-01-11,1,AUTOMOTIVE,3.0,3.0,NaN,NaN
19602,2013-01-12,1,AUTOMOTIVE,2.0,5.0,NaN,NaN
21384,2013-01-13,1,AUTOMOTIVE,2.0,2.0,NaN,NaN
23166,2013-01-14,1,AUTOMOTIVE,2.0,0.0,NaN,NaN
24948,2013-01-15,1,AUTOMOTIVE,1.0,2.0,0.0,NaN
26730,2013-01-16,1,AUTOMOTIVE,1.0,2.0,2.0,NaN
28512,2013-01-17,1,AUTOMOTIVE,1.0,2.0,3.0,NaN
30294,2013-01-18,1,AUTOMOTIVE,0.0,3.0,3.0,NaN
32076,2013-01-19,1,AUTOMOTIVE,5.0,2.0,5.0,NaN
33858,2013-01-20,1,AUTOMOTIVE,3.0,2.0,2.0,NaN
35640,2013-01-21,1,AUTOMOTIVE,1.0,2.0,0.0,NaN
37422,2013-01-22,1,AUTOMOTIVE,1.0,1.0,2.0,NaN
39204,2013-01-23,1,AUTOMOTIVE,3.0,1.0,2.0,NaN
40986,2013-01-24,1,AUTOMOTIVE,0.0,1.0,2.0,NaN
42768,2013-01-25,1,AUTOMOTIVE,5.0,0.0,3.0,NaN
44550,2013-01-26,1,AUTOMOTIVE,4.0,5.0,2.0,NaN
46332,2013-01-27,1,AUTOMOTIVE,2.0,3.0,2.0,NaN
48114,2013-01-28,1,AUTOMOTIVE,3.0,1.0,2.0,NaN
49896,2013-01-29,1,AUTOMOTIVE,2.0,1.0,1.0,0.0
51678,2013-01-30,1,AUTOMOTIVE,6.0,3.0,1.0,2.0
53460,2013-01-31,1,AUTOMOTIVE,0.0,0.0,1.0,3.0
55242,2013-02-01,1,AUTOMOTIVE,3.0,5.0,0.0,3.0
57024,2013-02-02,1,AUTOMOTIVE,0.0,4.0,5.0,5.0
58806,2013-02-03,1,AUTOMOTIVE,0.0,2.0,3.0,2.0
60588,2013-02-04,1,AUTOMOTIVE,5.0,3.0,1.0,0.0
62370,2013-02-05,1,AUTOMOTIVE,0.0,2.0,1.0,2.0
64152,2013-02-06,1,AUTOMOTIVE,1.0,6.0,3.0,2.0
65934,2013-02-07,1,AUTOMOTIVE,1.0,0.0,0.0,2.0
67716,2013-02-08,1,AUTOMOTIVE,2.0,3.0,5.0,3.0
69498,2013-02-09,1,AUTOMOTIVE,4.0,0.0,4.0,2.0

Cell 7 - Missing values

In [7]:
print(train["sales_lag_7"].isnull().sum())
print(train["sales_lag_14"].isnull().sum())
print(train["sales_lag_28"].isnull().sum())

12474
24948
49896

Cell 8 - Rolling Mean 7

In [8]:
train["rolling_mean_7"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).mean()
    )
)

Cell 9 - Rolling Mean 14

In [9]:
train["rolling_mean_14"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(14).mean()
    )
)

Cell 10 - Rolling Mean 28

In [10]:
train["rolling_mean_28"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(28).mean()
    )
)

Cell 11 - Check results

In [11]:
train[
    [
        "date",
        "sales",
        "sales_lag_7",
        "rolling_mean_7",
        "rolling_mean_14",
        "rolling_mean_28"
    ]
].head(40)

,date,sales,sales_lag_7,rolling_mean_7,rolling_mean_14,rolling_mean_28
0,2013-01-01,0.0,NaN,NaN,NaN,NaN
1782,2013-01-02,2.0,NaN,NaN,NaN,NaN
3564,2013-01-03,3.0,NaN,NaN,NaN,NaN
5346,2013-01-04,3.0,NaN,NaN,NaN,NaN
7128,2013-01-05,5.0,NaN,NaN,NaN,NaN
8910,2013-01-06,2.0,NaN,NaN,NaN,NaN
10692,2013-01-07,0.0,NaN,NaN,NaN,NaN
12474,2013-01-08,2.0,0.0,2.142857,NaN,NaN
14256,2013-01-09,2.0,2.0,2.428571,NaN,NaN
16038,2013-01-10,2.0,3.0,2.428571,NaN,NaN
17820,2013-01-11,3.0,3.0,2.285714,NaN,NaN
19602,2013-01-12,2.0,5.0,2.285714,NaN,NaN
21384,2013-01-13,2.0,2.0,1.857143,NaN,NaN
23166,2013-01-14,2.0,0.0,1.857143,NaN,NaN
24948,2013-01-15,1.0,2.0,2.142857,2.142857,NaN
26730,2013-01-16,1.0,2.0,2.000000,2.214286,NaN
28512,2013-01-17,1.0,2.0,1.857143,2.142857,NaN
30294,2013-01-18,0.0,3.0,1.714286,2.000000,NaN
32076,2013-01-19,5.0,2.0,1.285714,1.785714,NaN
33858,2013-01-20,3.0,2.0,1.714286,1.785714,NaN
35640,2013-01-21,1.0,2.0,1.857143,1.857143,NaN
37422,2013-01-22,1.0,1.0,1.714286,1.928571,NaN
39204,2013-01-23,3.0,1.0,1.714286,1.857143,NaN
40986,2013-01-24,0.0,1.0,2.000000,1.928571,NaN
42768,2013-01-25,5.0,0.0,1.857143,1.785714,NaN
44550,2013-01-26,4.0,5.0,2.571429,1.928571,NaN
46332,2013-01-27,2.0,3.0,2.428571,2.071429,NaN
48114,2013-01-28,3.0,1.0,2.285714,2.071429,NaN
49896,2013-01-29,2.0,1.0,2.571429,2.142857,2.142857
51678,2013-01-30,6.0,3.0,2.714286,2.214286,2.214286
53460,2013-01-31,0.0,0.0,3.142857,2.571429,2.357143
55242,2013-02-01,3.0,5.0,3.142857,2.500000,2.250000
57024,2013-02-02,0.0,4.0,2.857143,2.714286,2.250000
58806,2013-02-03,0.0,2.0,2.285714,2.357143,2.071429
60588,2013-02-04,5.0,3.0,2.000000,2.142857,2.000000
62370,2013-02-05,0.0,2.0,2.285714,2.428571,2.178571
64152,2013-02-06,1.0,6.0,2.000000,2.357143,2.107143
65934,2013-02-07,1.0,0.0,1.285714,2.214286,2.071429
67716,2013-02-08,2.0,3.0,1.428571,2.285714,2.035714
69498,2013-02-09,4.0,0.0,1.285714,2.071429,2.000000

Cell 12 - Missing values

In [12]:
print(train["rolling_mean_7"].isnull().sum())
print(train["rolling_mean_14"].isnull().sum())
print(train["rolling_mean_28"].isnull().sum())

12474
24948
49896

Cell 13 - Rolling Standard Deviation

In [13]:
train["rolling_std_7"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).std()
    )
)

Cell 14

In [14]:
train["rolling_std_28"] = (
    train.groupby(
        ["store_nbr", "family"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(28).std()
    )
)

Cell 15

In [15]:
print(train["rolling_std_7"].isnull().sum())
print(train["rolling_std_28"].isnull().sum())

12474
49896

Cell 16 - Fill NaNs

In [16]:
lag_features = [
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_28",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28",
    "rolling_std_7",
    "rolling_std_28"
]

train[lag_features] = train[lag_features].fillna(0)

Cell 17 - Everything should be zero

In [17]:
train[lag_features].isnull().sum()

sales_lag_7        0
sales_lag_14       0
sales_lag_28       0
rolling_mean_7     0
rolling_mean_14    0
rolling_mean_28    0
rolling_std_7      0
rolling_std_28     0
dtype: int64

Cell 18 - Save advanced dataset

In [18]:
ADVANCED_DIR = BASE_DIR / "data" / "advanced"

ADVANCED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

train.to_csv(
    ADVANCED_DIR / "train_advanced.csv",
    index=False
)

print(train.shape)

(3000888, 29)